<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup Condition="Exists('..\..\CursorFX.Core\CursorFX.Core.csproj')">
    <ProjectReference Include="..\..\CursorFX.Core\CursorFX.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="!Exists('..\..\CursorFX.Core\CursorFX.Core.csproj')">
    <Reference Include="CursorFX.Core">
      <HintPath>..\Fluxor.PluginSdk\CursorFX.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
</Project>
