<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CursorFX.Core\CursorFX.Core.csproj" />
    <ProjectReference Include="..\CursorFX.Platform\CursorFX.Platform.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
