<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CursorFX.Core\CursorFX.Core.csproj" />
    <ProjectReference Include="..\CursorFX.Rendering\CursorFX.Rendering.csproj" />
    <ProjectReference Include="..\CursorFX.Effects\CursorFX.Effects.csproj" />
    <ProjectReference Include="..\CursorFX.Platform\CursorFX.Platform.csproj" />
    <Resource Include="Assets\FluxorIco.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Fluxor</AssemblyName>
    <RootNamespace>CursorFX.App</RootNamespace>
    <Version>0.0.4</Version>
    <AssemblyVersion>0.0.4.0</AssemblyVersion>
    <FileVersion>0.0.4.0</FileVersion>
    <InformationalVersion>0.0.4</InformationalVersion>
    <Company>Dokzya_dev</Company>
    <Product>Fluxor</Product>
    <Authors>Dokzya_dev</Authors>
    <ApplicationIcon>Assets\FluxorIco.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Templates\plugin-authoring-guide.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
