using System.Globalization;
using CursorFX.Core.Models;

namespace CursorFX.App.Services;

public sealed class LocalizationService
{
    private static readonly IReadOnlyList<LocalizationOption> SupportedLanguages =
    [
        new("en", "English"),
        new("uk", "Українська"),
        new("ru", "Русский")
    ];

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Strings =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["settings.windowTitle"] = "Fluxor · Settings",
                ["settings.heading"] = "Fluxor Settings",
                ["settings.intro"] = "Control how Fluxor starts, behaves in the background, and which language should be used for the interface.",
                ["settings.startup"] = "Startup",
                ["settings.launchOnStartup"] = "Launch Fluxor when Windows starts",
                ["settings.backgroundMode"] = "Background Mode",
                ["settings.runInBackground"] = "Keep Fluxor running in the tray when the main window is closed or minimized",
                ["settings.renderGuard"] = "Render Guard",
                ["settings.pauseWhenCursorHidden"] = "Pause effects when a fullscreen app hides the cursor",
                ["settings.language"] = "Language",
                ["settings.useSystemLanguage"] = "Use system language automatically",
                ["settings.languageLabel"] = "Application language",
                ["settings.languageHint"] = "Language changes apply to newly opened windows first. A full UI rollout will continue in upcoming updates.",
                ["settings.pluginTools"] = "Plugin Tools",
                ["settings.pluginToolsHint"] = "Open the authoring guide or the plugin workspace without keeping those actions on the main screen.",
                ["settings.openGuide"] = "Open Authoring Guide",
                ["settings.openPluginsFolder"] = "Open Plugins Folder",
                ["settings.cancel"] = "Cancel",
                ["settings.apply"] = "Apply",
                ["settings.updated"] = "Application settings updated.",
                ["import.windowTitle"] = "Fluxor | Import Plugin",
                ["import.heading"] = "Import Plugin",
                ["import.intro"] = "Choose a plugin DLL. Fluxor will read plugin metadata and parameter schema directly from the assembly, generate the profile automatically, and copy companion runtime files when they exist.",
                ["import.assemblyTitle"] = "DLL Assembly File",
                ["import.assemblyHint"] = "The DLL must contain a public ICursorEffectPlugin implementation and expose settings via GetParameters().",
                ["import.browseDll"] = "Browse DLL File",
                ["import.openPluginsFolder"] = "Open Plugins Folder",
                ["import.pluginTypeTitle"] = "Plugin Type",
                ["import.pluginTypeHint"] = "If the DLL contains multiple plugins, choose which one should be imported.",
                ["import.installModeTitle"] = "Install Mode",
                ["import.installModeHint"] = "Fluxor can either import this DLL as a new profile or replace a matching imported plugin while preserving compatible settings.",
                ["import.replaceExisting"] = "Replace the matching imported profile instead of creating a new one",
                ["import.importAsNew"] = "No matching imported profile was detected. Fluxor will import this DLL as a new profile.",
                ["import.match.none"] = "No matching imported profile detected.",
                ["import.match.summary"] = "Matching imported profile: {0} ({1})\nMatched by {2}.",
                ["import.match.reason.pluginId"] = "plugin ID",
                ["import.match.reason.entryType"] = "entry type",
                ["import.previewTitle"] = "Import Preview",
                ["import.previewHint"] = "Fluxor will generate the plugin profile directly from the selected assembly metadata.",
                ["import.preview.displayName"] = "Display name",
                ["import.preview.pluginId"] = "Plugin ID",
                ["import.preview.entryType"] = "Entry type",
                ["import.preview.noSelection"] = "No plugin type selected yet.",
                ["import.preview.summary"] = "{0} - {1}\n{2}",
                ["import.preview.notSelected"] = "Not selected",
                ["import.preview.generatedId"] = "Will be generated from the selected plugin.",
                ["import.preview.chooseType"] = "Select a plugin type to preview it.",
                ["import.iconTitle"] = "Plugin Icon",
                ["import.iconHint"] = "Optional image for the plugin card. Fluxor will copy it to the plugin catalog and render it as a square icon.",
                ["import.chooseIcon"] = "Choose Icon",
                ["import.clearIcon"] = "Clear Icon",
                ["import.iconPlaceholder"] = "Icon",
                ["import.iconNone"] = "No icon selected.",
                ["import.cancel"] = "Cancel",
                ["import.confirm"] = "Import Plugin",
                ["import.validation.title"] = "Validation",
                ["import.validation.chooseDll"] = "Choose a DLL file.",
                ["import.validation.choosePluginType"] = "Choose a plugin type from the DLL.",
                ["guide.windowTitle"] = "Fluxor · Plugin Authoring Guide",
                ["guide.heading"] = "Plugin Authoring Guide",
                ["guide.intro"] = "How to build DLL-only Fluxor plugins, expose parameter schema from code, and avoid runtime or import failures.",
                ["guide.copy"] = "Copy Guide",
                ["guide.close"] = "Close",
                ["guide.missing"] = "Plugin authoring guide was not found.",
                ["main.importedStatus"] = "Plugin {0} imported from DLL.",
                ["main.heroSubtitle"] = "A cleaner control center for cursor effects, built-in styles, and DLL plugins.",
                ["main.applicationSettings"] = "Application Settings",
                ["main.importPlugin"] = "Import Plugin",
                ["main.importArchive"] = "Import Archive",
                ["main.importMenu"] = "Import...",
                ["main.currentProfile"] = "Current Profile",
                ["main.moreActions"] = "More Actions",
                ["main.saveSettings"] = "Save Settings",
                ["main.resetProfile"] = "Reset Profile",
                ["main.chooseIcon"] = "Choose Icon",
                ["main.clearIcon"] = "Clear Icon",
                ["main.openPluginFolder"] = "Open Plugin Folder",
                ["main.saveAsProfile"] = "Save as Profile",
                ["main.exportProfile"] = "Export Profile",
                ["main.deletePlugin"] = "Delete Plugin",
                ["main.pickColor"] = "Pick",
                ["main.enabledToggle"] = "Enabled",
                ["main.status"] = "Status",
                ["main.generalControls"] = "General Controls",
                ["main.masterOpacity"] = "Master opacity",
                ["main.fpsCap"] = "FPS cap",
                ["main.cursorAttach"] = "Cursor attach",
                ["main.effectQuality"] = "Effect quality",
                ["main.effectQualityHint"] = "Controls internal built-in effect density and caps. Lower quality is lighter, higher quality keeps more particles, nodes, and pulses.",
                ["main.quality.low"] = "Low",
                ["main.quality.balanced"] = "Balanced",
                ["main.quality.high"] = "High",
                ["main.cursorAttachHint"] = "Use higher attach values when you want built-in effects to stay visually glued to the cursor during fast motion.",
                ["main.pluginAuthoring"] = "Plugin Authoring",
                ["main.pluginAuthoringHint"] = "Fluxor supports DLL-only plugins. Open the guide to see how to create a plugin, expose parameters from code, build the DLL, and import it into the app.",
                ["main.openAuthoringGuide"] = "Open Authoring Guide",
                ["main.profileControls"] = "Profile Controls",
                ["main.profileControlsHint"] = "Core controls are shown first. Advanced controls stay available but out of the way.",
                ["main.basic"] = "Basic",
                ["main.basicHint"] = "The most useful controls for shaping the current profile quickly.",
                ["main.advanced"] = "Advanced",
                ["main.advancedHint"] = "Less common controls for motion tuning, noise, spawn rules, and profile-specific behavior.",
                ["main.pluginDiagnostics"] = "Plugin Diagnostics",
                ["main.diag.status"] = "Status",
                ["main.diag.assembly"] = "Assembly",
                ["main.diag.assemblyPath"] = "Assembly path",
                ["main.diag.entryType"] = "Entry type",
                ["main.diag.loadedAt"] = "Loaded at",
                ["main.diag.lastError"] = "Last error",
                ["main.diag.reload"] = "Reload",
                ["main.diag.revealFiles"] = "Reveal Files",
                ["main.diag.useSafeProfile"] = "Use Safe Profile",
                ["main.diag.warning"] = "Warning",
                ["main.diag.status.loaded"] = "Loaded",
                ["main.diag.status.idle"] = "Idle",
                ["main.diag.status.error"] = "Error",
                ["main.diag.status.broken"] = "Broken",
                ["main.diag.bool.yes"] = "yes",
                ["main.diag.bool.no"] = "no",
                ["main.diag.context"] = "Cursor snapshot: {0} | Backdrop sample: {1} | Cursor visible: {2}",
                ["main.diag.warning.assemblyMissing"] = "The plugin DLL is missing from the expected catalog path. Re-import or replace the plugin package.",
                ["main.diag.warning.configIssue"] = "The imported plugin profile is missing required runtime metadata. Re-import the plugin or replace it with a newer build.",
                ["main.diag.warning.runtimeError"] = "The plugin runtime failed while loading or rendering. Try Reload first, then replace the plugin if the error persists.",
                ["main.diag.warning.hiddenCursor"] = "The cursor is currently hidden. Cursor-locked plugins may not render until the cursor becomes visible again.",
                ["main.diag.warning.noBackdrop"] = "Backdrop sampling is not available right now. Plugins that distort the visible image may look incomplete.",
                ["main.diag.warning.noSnapshot"] = "Cursor snapshot is not available right now. Cursor-shape contour plugins may not render correctly.",
                ["main.diag.warning.none"] = "Runtime context looks healthy.",
                ["main.startupRecovery.keepSafeProfile"] = "Keep Safe Profile",
                ["main.startupRecovery.openPluginsFolder"] = "Open Plugins Folder",
                ["main.profiles"] = "Profiles",
                ["main.profilesHint"] = "Built-in styles stay separate from imported DLL plugins so the library is easier to scan.",
                ["main.builtInProfiles"] = "Built-in Profiles",
                ["main.importedPlugins"] = "Imported Plugins",
                ["main.importShort"] = "Import",
                ["main.iconPlaceholder"] = "Icon",
                ["main.autosaveReady"] = "Settings are synced automatically.",
                ["main.noImportedPlugins"] = "No imported plugins yet.",
                ["main.importedPluginsSummary"] = "Imported plugins sorted by newest first ({0}).",
                ["main.builtInProfilesSummary"] = "{0} built-in profiles.",
                ["main.selectedPlugin.none"] = "No plugin selected",
                ["main.selectedPlugin.prompt"] = "Select a plugin profile.",
                ["main.runtimeKind.imported"] = "Imported DLL plugin",
                ["main.runtimeKind.builtIn"] = "Built-in profile",
                ["main.status.profileChanged"] = "Plugin profile changed.",
                ["main.status.generalChanged"] = "General settings changed.",
                ["main.status.pluginParametersChanged"] = "Plugin parameters changed.",
                ["main.status.pluginDeleted"] = "Plugin {0} deleted.",
                ["main.status.pluginDeletedFilesBusy"] = "Plugin profile removed, but some runtime files are still in use: {0}",
                ["main.status.savedAt"] = "Saved at {0}",
                ["main.status.pluginReset"] = "Plugin {0} reset to defaults.",
                ["main.status.iconUpdated"] = "Icon updated for {0}.",
                ["main.status.iconCleared"] = "Icon cleared for {0}.",
                ["main.status.folderOpened"] = "Opened {0}.",
                ["main.status.builtInLocked"] = "Built-in profiles cannot be deleted.",
                ["main.effectOperation.switchTitle"] = "Applying Profile",
                ["main.effectOperation.switchMessage"] = "Fluxor is updating the current cursor profile and rendering state.",
                ["main.effectOperation.importTitle"] = "Installing Plugin",
                ["main.effectOperation.importMessage"] = "Fluxor is importing the plugin DLL and preparing the cursor effect.",
                ["main.effectOperation.importArchiveTitle"] = "Importing Profile Archive",
                ["main.effectOperation.importArchiveMessage"] = "Fluxor is unpacking the profile archive and preparing the imported effect.",
                ["main.effectOperation.settingsTitle"] = "Updating Settings",
                ["main.effectOperation.settingsMessage"] = "Fluxor is applying the updated settings and refreshing the cursor effect.",
                ["main.effectOperation.saveTitle"] = "Saving Profile",
                ["main.effectOperation.saveMessage"] = "Fluxor is saving the current cursor effect settings.",
                ["main.effectOperation.saveAsTitle"] = "Saving Profile Copy",
                ["main.effectOperation.saveAsMessage"] = "Fluxor is creating a new profile from the current settings.",
                ["main.effectOperation.resetTitle"] = "Resetting Profile",
                ["main.effectOperation.resetMessage"] = "Fluxor is restoring the current cursor profile to its default settings.",
                ["main.effectOperation.exportTitle"] = "Exporting Profile",
                ["main.effectOperation.exportMessage"] = "Fluxor is packing the current profile and its required assets into an archive.",
                ["main.effectOperation.reloadTitle"] = "Reloading Plugin",
                ["main.effectOperation.reloadMessage"] = "Fluxor is reloading the current plugin runtime and refreshing diagnostics.",
                ["main.archiveImport.dialogTitle"] = "Import Fluxor Profile Archive",
                ["main.archiveImport.dialogFilter"] = "Fluxor profile (*.fluxorprofile)|*.fluxorprofile|Legacy Fluxor profile archive (*.fluxor-profile.zip)|*.fluxor-profile.zip|Zip archive (*.zip)|*.zip",
                ["main.archiveImport.success"] = "Profile {0} imported from archive.",
                ["main.archiveImport.replaced"] = "Profile {0} was updated from archive.",
                ["main.archiveExport.dialogTitle"] = "Export Fluxor Profile Archive",
                ["main.archiveExport.dialogFilter"] = "Fluxor profile (*.fluxorprofile)|*.fluxorprofile|Legacy Fluxor profile archive (*.fluxor-profile.zip)|*.fluxor-profile.zip|Zip archive (*.zip)|*.zip",
                ["main.archiveExport.success"] = "Profile archive saved as {0}.",
                ["main.status.profileSavedAs"] = "Profile saved as {0}.",
                ["main.status.pluginReloaded"] = "Plugin runtime reloaded.",
                ["main.status.pluginFilesRevealed"] = "Plugin files revealed in Explorer.",
                ["main.status.safeProfileActivated"] = "Switched to safe profile: {0}.",
                ["main.importedStatusReplaced"] = "Plugin {0} was updated from DLL.",
                ["main.dialog.deletePluginTitle"] = "Delete Plugin",
                ["main.dialog.deletePluginBody"] = "Delete plugin '{0}'?\n\nThis removes the profile from the Fluxor plugin catalog. For external plugins Fluxor will also try to remove the DLL if no other profile references it.",
                ["main.dialog.deletePluginFailed"] = "Delete Plugin Failed",
                ["main.dialog.pluginIconFailed"] = "Plugin Icon Failed",
                ["main.dialog.openFolderFailed"] = "Open Folder Failed",
                ["main.dialog.pluginImportFailed"] = "Plugin Import Failed",
                ["main.dialog.archiveImportFailed"] = "Archive Import Failed",
                ["main.dialog.archiveExportFailed"] = "Archive Export Failed",
                ["main.dialog.saveProfileFailed"] = "Save Profile Failed",
                ["main.dialog.chooseIconTitle"] = "Choose icon for {0}",
                ["saveProfile.windowTitle"] = "Fluxor · Save Profile",
                ["saveProfile.heading"] = "Save as Separate Profile",
                ["saveProfile.intro"] = "Create a standalone profile from the current effect settings. The saved profile can be tuned separately and shared later.",
                ["saveProfile.name"] = "Profile name",
                ["saveProfile.description"] = "Description",
                ["saveProfile.cancel"] = "Cancel",
                ["saveProfile.confirm"] = "Save Profile",
                ["saveProfile.validation.title"] = "Validation",
                ["saveProfile.validation.nameRequired"] = "Enter a profile name.",
                ["saveProfile.copySuffix"] = "Copy",
                ["colorPicker.windowTitle"] = "Fluxor · Color Picker",
                ["archivePreview.windowTitle"] = "Fluxor | Archive Preview",
                ["archivePreview.heading"] = "Archive Preview",
                ["archivePreview.introImport"] = "Review the imported profile package before Fluxor adds it to your profile library.",
                ["archivePreview.introReplace"] = "Fluxor found an existing profile with the same ID. Review the archive and choose whether to replace the existing profile or import a separate copy.",
                ["archivePreview.name"] = "Name",
                ["archivePreview.id"] = "Profile ID",
                ["archivePreview.runtime"] = "Runtime",
                ["archivePreview.parameters"] = "Parameters",
                ["archivePreview.icon"] = "Icon included",
                ["archivePreview.assembly"] = "Plugin DLL included",
                ["archivePreview.runtimeBuiltIn"] = "Built-in profile",
                ["archivePreview.runtimeImported"] = "Imported DLL plugin",
                ["archivePreview.yes"] = "Yes",
                ["archivePreview.no"] = "No",
                ["archivePreview.noDescription"] = "No description provided.",
                ["archivePreview.conflictTitle"] = "Import Mode",
                ["archivePreview.noConflict"] = "No conflicting profile was found. Fluxor will import this archive as a new profile.",
                ["archivePreview.replaceSummary"] = "Fluxor can replace the existing profile '{0}' or import this archive as a separate copy.",
                ["archivePreview.warningsTitle"] = "Warnings",
                ["archivePreview.warnings.none"] = "No validation warnings were detected.",
                ["archivePreview.cancel"] = "Cancel",
                ["archivePreview.import"] = "Import",
                ["archivePreview.importCopy"] = "Import Copy",
                ["archivePreview.replace"] = "Replace Existing",
                ["startup.recovery.title"] = "Fluxor started in safe mode",
                ["startup.recovery.missingProfile"] = "The previously selected profile '{0}' could not be found, so Fluxor switched to the safe profile '{1}'.",
                ["startup.recovery.missingAssembly"] = "The imported profile '{0}' is missing its plugin DLL, so Fluxor switched to the safe profile '{1}'.",
                ["startup.recovery.invalidMetadata"] = "The imported profile '{0}' is missing required runtime metadata, so Fluxor switched to the safe profile '{1}'.",
                ["startup.recovery.renderFailedTitle"] = "Fluxor rendering could not fully start",
                ["startup.recovery.renderFailedMessage"] = "Fluxor kept the main window open so you can review settings and diagnostics.\n\n{0}",
                ["colorPicker.cancel"] = "Cancel",
                ["colorPicker.confirm"] = "OK",
                ["colorPicker.hex"] = "HEX"
            },
            ["uk"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["settings.windowTitle"] = "Fluxor · Налаштування",
                ["settings.heading"] = "Налаштування Fluxor",
                ["settings.intro"] = "Керуйте автозапуском Fluxor, роботою у фоновому режимі та мовою інтерфейсу.",
                ["settings.startup"] = "Автозапуск",
                ["settings.launchOnStartup"] = "Запускати Fluxor разом із Windows",
                ["settings.backgroundMode"] = "Фоновий режим",
                ["settings.runInBackground"] = "Залишати Fluxor у треї після закриття або згортання головного вікна",
                ["settings.renderGuard"] = "Захист рендера",
                ["settings.pauseWhenCursorHidden"] = "Призупиняти ефекти, коли fullscreen-застосунок ховає курсор",
                ["settings.language"] = "Мова",
                ["settings.useSystemLanguage"] = "Автоматично використовувати системну мову",
                ["settings.languageLabel"] = "Мова застосунку",
                ["settings.languageHint"] = "Зміна мови спершу застосовується до нових вікон. Повна локалізація решти UI буде розширюватися в наступних оновленнях.",
                ["settings.pluginTools"] = "Інструменти плагінів",
                ["settings.pluginToolsHint"] = "Відкрийте гайд або робочу папку плагінів, не займаючи цими діями головний екран.",
                ["settings.openGuide"] = "Відкрити гайд",
                ["settings.openPluginsFolder"] = "Відкрити папку плагінів",
                ["settings.cancel"] = "Скасувати",
                ["settings.apply"] = "Застосувати",
                ["settings.updated"] = "Параметри застосунку оновлено.",
                ["import.windowTitle"] = "Fluxor | Імпорт плагіна",
                ["import.heading"] = "Імпорт плагіна",
                ["import.intro"] = "Оберіть DLL плагіна. Fluxor прочитає metadata та схему параметрів прямо зі збірки, автоматично згенерує профіль і скопіює супутні runtime-файли, якщо вони існують.",
                ["import.assemblyTitle"] = "DLL-файл збірки",
                ["import.assemblyHint"] = "DLL має містити публічну реалізацію ICursorEffectPlugin і описувати параметри через GetParameters().",
                ["import.browseDll"] = "Обрати DLL",
                ["import.openPluginsFolder"] = "Відкрити папку Plugins",
                ["import.pluginTypeTitle"] = "Тип плагіна",
                ["import.pluginTypeHint"] = "Якщо DLL містить кілька плагінів, оберіть, який саме потрібно імпортувати.",
                ["import.previewTitle"] = "Попередній перегляд імпорту",
                ["import.previewHint"] = "Fluxor згенерує профіль плагіна прямо з metadata вибраної збірки.",
                ["import.preview.displayName"] = "Назва",
                ["import.preview.pluginId"] = "Plugin ID",
                ["import.preview.entryType"] = "Entry type",
                ["import.iconTitle"] = "Іконка плагіна",
                ["import.iconHint"] = "Необов’язкове зображення для картки плагіна. Fluxor скопіює його в каталог плагінів і покаже як квадратну іконку.",
                ["import.chooseIcon"] = "Обрати іконку",
                ["import.clearIcon"] = "Очистити іконку",
                ["import.iconPlaceholder"] = "Іконка",
                ["import.iconNone"] = "Іконку не вибрано.",
                ["import.cancel"] = "Скасувати",
                ["import.confirm"] = "Імпортувати плагін",
                ["import.validation.title"] = "Перевірка",
                ["import.validation.chooseDll"] = "Оберіть DLL-файл.",
                ["import.validation.choosePluginType"] = "Оберіть тип плагіна з DLL.",
                ["import.installModeTitle"] = "Режим встановлення",
                ["import.installModeHint"] = "Fluxor може або імпортувати цю DLL як новий профіль, або замінити відповідний імпортований плагін зі збереженням сумісних параметрів.",
                ["import.replaceExisting"] = "Замінити відповідний імпортований профіль замість створення нового",
                ["import.importAsNew"] = "Відповідний імпортований профіль не знайдено. Fluxor імпортує цю DLL як новий профіль.",
                ["import.match.none"] = "Відповідний імпортований профіль не знайдено.",
                ["import.match.summary"] = "Відповідний імпортований профіль: {0} ({1})\nЗбіг за: {2}.",
                ["import.match.reason.pluginId"] = "plugin ID",
                ["import.match.reason.entryType"] = "entry type",
                ["guide.windowTitle"] = "Fluxor · Гайд зі створення плагінів",
                ["guide.heading"] = "Гайд зі створення плагінів",
                ["guide.intro"] = "Як створювати DLL-only плагіни для Fluxor, описувати схему параметрів у коді та уникати помилок імпорту чи runtime.",
                ["guide.copy"] = "Скопіювати гайд",
                ["guide.close"] = "Закрити",
                ["guide.missing"] = "Гайд зі створення плагінів не знайдено.",
                ["main.importedStatus"] = "Плагін {0} імпортовано з DLL.",
                ["main.heroSubtitle"] = "Чистіший центр керування ефектами курсора, вбудованими стилями та DLL-плагінами.",
                ["main.applicationSettings"] = "Налаштування застосунку",
                ["main.importPlugin"] = "Імпортувати плагін",
                ["main.currentProfile"] = "Поточний профіль",
                ["main.moreActions"] = "Додатково",
                ["main.saveSettings"] = "Зберегти параметри",
                ["main.resetProfile"] = "Скинути профіль",
                ["main.chooseIcon"] = "Обрати іконку",
                ["main.clearIcon"] = "Очистити іконку",
                ["main.openPluginFolder"] = "Відкрити папку плагінів",
                ["main.deletePlugin"] = "Видалити плагін",
                ["main.status"] = "Стан",
                ["main.generalControls"] = "Загальні параметри",
                ["main.masterOpacity"] = "Загальна прозорість",
                ["main.fpsCap"] = "Ліміт FPS",
                ["main.cursorAttach"] = "Прилипання до курсора",
                ["main.effectQuality"] = "Якість ефектів",
                ["main.effectQualityHint"] = "Керує внутрішньою щільністю та лімітами вбудованих ефектів. Нижча якість легша, вища зберігає більше партиклів, вузлів і імпульсів.",
                ["main.quality.low"] = "Низька",
                ["main.quality.balanced"] = "Збалансована",
                ["main.quality.high"] = "Висока",
                ["main.cursorAttachHint"] = "Збільшуйте параметр, якщо хочете, щоб вбудовані ефекти візуально майже не відставали від курсора навіть під час різких рухів.",
                ["main.pluginAuthoring"] = "Створення плагінів",
                ["main.pluginAuthoringHint"] = "Fluxor підтримує DLL-only плагіни. Відкрий гайд, щоб побачити, як створити плагін, описати параметри в коді, зібрати DLL і імпортувати її в застосунок.",
                ["main.openAuthoringGuide"] = "Відкрити гайд",
                ["main.profileControls"] = "Параметри профілю",
                ["main.profileControlsHint"] = "Основні параметри показані першими. Розширені залишаються доступними, але не заважають.",
                ["main.basic"] = "Основні",
                ["main.basicHint"] = "Найкорисніші параметри для швидкого налаштування поточного профілю.",
                ["main.advanced"] = "Розширені",
                ["main.advancedHint"] = "Рідше вживані параметри для motion tuning, noise, spawn rules та профільної логіки.",
                ["main.pluginDiagnostics"] = "Діагностика плагіна",
                ["main.diag.status"] = "Стан",
                ["main.diag.assembly"] = "Збірка",
                ["main.diag.assemblyPath"] = "Шлях до збірки",
                ["main.diag.entryType"] = "Entry type",
                ["main.diag.loadedAt"] = "Завантажено",
                ["main.diag.lastError"] = "Остання помилка",
                ["main.diag.warning"] = "Попередження",
                ["main.diag.reload"] = "Перезавантажити",
                ["main.diag.revealFiles"] = "Показати файли",
                ["main.diag.useSafeProfile"] = "Безпечний профіль",
                ["main.diag.status.loaded"] = "Завантажено",
                ["main.diag.status.idle"] = "Очікування",
                ["main.diag.status.error"] = "Помилка",
                ["main.diag.status.broken"] = "Пошкоджено",
                ["main.diag.bool.yes"] = "так",
                ["main.diag.bool.no"] = "ні",
                ["main.diag.context"] = "Знімок курсора: {0} | Backdrop sample: {1} | Курсор видимий: {2}",
                ["main.diag.warning.assemblyMissing"] = "DLL плагіна відсутня в очікуваному каталозі. Повторно імпортуйте або замініть пакет плагіна.",
                ["main.diag.warning.configIssue"] = "Імпортований профіль плагіна не містить обов’язкових runtime-метаданих. Повторно імпортуйте плагін або замініть його новішою збіркою.",
                ["main.diag.warning.runtimeError"] = "Runtime плагіна впав під час завантаження або рендера. Спершу спробуйте перезавантаження, а потім заміну плагіна, якщо помилка лишається.",
                ["main.diag.warning.hiddenCursor"] = "Курсор зараз прихований. Плагіни, прив’язані до курсора, можуть не рендеритися, доки курсор знову не стане видимим.",
                ["main.diag.warning.noBackdrop"] = "Backdrop sampling зараз недоступний. Плагіни, які викривляють видиме зображення, можуть виглядати неповно.",
                ["main.diag.warning.noSnapshot"] = "Знімок курсора зараз недоступний. Контурні плагіни за формою курсора можуть працювати некоректно.",
                ["main.diag.warning.none"] = "Runtime-контекст виглядає коректно.",
                ["main.profiles"] = "Профілі",
                ["main.profilesHint"] = "Вбудовані стилі відокремлені від імпортованих DLL-плагінів, щоб бібліотеку було легше сканувати.",
                ["main.builtInProfiles"] = "Вбудовані профілі",
                ["main.importedPlugins"] = "Імпортовані плагіни",
                ["main.importShort"] = "Імпорт",
                ["main.iconPlaceholder"] = "Іконка",
                ["main.autosaveReady"] = "Параметри синхронізуються автоматично.",
                ["main.noImportedPlugins"] = "Імпортованих плагінів ще немає.",
                ["main.importedPluginsSummary"] = "Імпортовані плагіни відсортовано від найновіших ({0}).",
                ["main.builtInProfilesSummary"] = "Вбудованих профілів: {0}."
            },
            ["ru"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["settings.windowTitle"] = "Fluxor · Настройки",
                ["settings.heading"] = "Настройки Fluxor",
                ["settings.intro"] = "Управляйте автозапуском Fluxor, фоновым режимом и языком интерфейса.",
                ["settings.startup"] = "Автозапуск",
                ["settings.launchOnStartup"] = "Запускать Fluxor вместе с Windows",
                ["settings.backgroundMode"] = "Фоновый режим",
                ["settings.runInBackground"] = "Оставлять Fluxor в трее после закрытия или сворачивания главного окна",
                ["settings.renderGuard"] = "Защита рендера",
                ["settings.pauseWhenCursorHidden"] = "Приостанавливать эффекты, когда fullscreen-приложение скрывает курсор",
                ["settings.language"] = "Язык",
                ["settings.useSystemLanguage"] = "Автоматически использовать системный язык",
                ["settings.languageLabel"] = "Язык приложения",
                ["settings.languageHint"] = "Смена языка сначала применяется к новым окнам. Полная локализация остального UI будет расширяться в следующих обновлениях.",
                ["settings.pluginTools"] = "Инструменты плагинов",
                ["settings.pluginToolsHint"] = "Откройте гайд или рабочую папку плагинов, не занимая этими действиями главный экран.",
                ["settings.openGuide"] = "Открыть гайд",
                ["settings.openPluginsFolder"] = "Открыть папку плагинов",
                ["settings.cancel"] = "Отмена",
                ["settings.apply"] = "Применить",
                ["settings.updated"] = "Параметры приложения обновлены.",
                ["import.windowTitle"] = "Fluxor | Импорт плагина",
                ["import.heading"] = "Импорт плагина",
                ["import.intro"] = "Выберите DLL плагина. Fluxor прочитает metadata и схему параметров прямо из сборки, автоматически создаст профиль и скопирует сопутствующие runtime-файлы, если они существуют.",
                ["import.assemblyTitle"] = "DLL-файл сборки",
                ["import.assemblyHint"] = "DLL должна содержать публичную реализацию ICursorEffectPlugin и описывать параметры через GetParameters().",
                ["import.browseDll"] = "Выбрать DLL",
                ["import.openPluginsFolder"] = "Открыть папку Plugins",
                ["import.pluginTypeTitle"] = "Тип плагина",
                ["import.pluginTypeHint"] = "Если DLL содержит несколько плагинов, выберите, какой именно нужно импортировать.",
                ["import.previewTitle"] = "Предпросмотр импорта",
                ["import.previewHint"] = "Fluxor сгенерирует профиль плагина прямо из metadata выбранной сборки.",
                ["import.preview.displayName"] = "Название",
                ["import.preview.pluginId"] = "Plugin ID",
                ["import.preview.entryType"] = "Entry type",
                ["import.iconTitle"] = "Иконка плагина",
                ["import.iconHint"] = "Необязательное изображение для карточки плагина. Fluxor скопирует его в каталог плагинов и покажет как квадратную иконку.",
                ["import.chooseIcon"] = "Выбрать иконку",
                ["import.clearIcon"] = "Очистить иконку",
                ["import.iconPlaceholder"] = "Иконка",
                ["import.iconNone"] = "Иконка не выбрана.",
                ["import.cancel"] = "Отмена",
                ["import.confirm"] = "Импортировать плагин",
                ["import.validation.title"] = "Проверка",
                ["import.validation.chooseDll"] = "Выберите DLL-файл.",
                ["import.validation.choosePluginType"] = "Выберите тип плагина из DLL.",
                ["import.installModeTitle"] = "Режим установки",
                ["import.installModeHint"] = "Fluxor может либо импортировать эту DLL как новый профиль, либо заменить соответствующий импортированный плагин с сохранением совместимых параметров.",
                ["import.replaceExisting"] = "Заменить соответствующий импортированный профиль вместо создания нового",
                ["import.importAsNew"] = "Соответствующий импортированный профиль не найден. Fluxor импортирует эту DLL как новый профиль.",
                ["import.match.none"] = "Соответствующий импортированный профиль не найден.",
                ["import.match.summary"] = "Соответствующий импортированный профиль: {0} ({1})\nСовпадение по: {2}.",
                ["import.match.reason.pluginId"] = "plugin ID",
                ["import.match.reason.entryType"] = "entry type",
                ["guide.windowTitle"] = "Fluxor · Гайд по созданию плагинов",
                ["guide.heading"] = "Гайд по созданию плагинов",
                ["guide.intro"] = "Как создавать DLL-only плагины для Fluxor, описывать схему параметров в коде и избегать ошибок импорта или runtime.",
                ["guide.copy"] = "Скопировать гайд",
                ["guide.close"] = "Закрыть",
                ["guide.missing"] = "Гайд по созданию плагинов не найден.",
                ["main.importedStatus"] = "Плагин {0} импортирован из DLL.",
                ["main.heroSubtitle"] = "Более чистый центр управления эффектами курсора, встроенными стилями и DLL-плагинами.",
                ["main.applicationSettings"] = "Настройки приложения",
                ["main.importPlugin"] = "Импортировать плагин",
                ["main.currentProfile"] = "Текущий профиль",
                ["main.moreActions"] = "Дополнительно",
                ["main.saveSettings"] = "Сохранить параметры",
                ["main.resetProfile"] = "Сбросить профиль",
                ["main.chooseIcon"] = "Выбрать иконку",
                ["main.clearIcon"] = "Очистить иконку",
                ["main.openPluginFolder"] = "Открыть папку плагинов",
                ["main.deletePlugin"] = "Удалить плагин",
                ["main.status"] = "Статус",
                ["main.generalControls"] = "Общие параметры",
                ["main.masterOpacity"] = "Общая прозрачность",
                ["main.fpsCap"] = "Лимит FPS",
                ["main.cursorAttach"] = "Прилипание к курсору",
                ["main.effectQuality"] = "Качество эффектов",
                ["main.effectQualityHint"] = "Управляет внутренней плотностью и лимитами встроенных эффектов. Низкое качество легче, высокое сохраняет больше частиц, узлов и импульсов.",
                ["main.quality.low"] = "Низкое",
                ["main.quality.balanced"] = "Сбалансированное",
                ["main.quality.high"] = "Высокое",
                ["main.cursorAttachHint"] = "Увеличивайте параметр, если хотите, чтобы встроенные эффекты визуально почти не отставали от курсора даже при резких движениях.",
                ["main.pluginAuthoring"] = "Создание плагинов",
                ["main.pluginAuthoringHint"] = "Fluxor поддерживает DLL-only плагины. Откройте гайд, чтобы увидеть, как создать плагин, описать параметры в коде, собрать DLL и импортировать её в приложение.",
                ["main.openAuthoringGuide"] = "Открыть гайд",
                ["main.profileControls"] = "Параметры профиля",
                ["main.profileControlsHint"] = "Основные параметры показаны первыми. Расширенные остаются доступными, но не мешают.",
                ["main.basic"] = "Основные",
                ["main.basicHint"] = "Самые полезные параметры для быстрого изменения текущего профиля.",
                ["main.advanced"] = "Расширенные",
                ["main.advancedHint"] = "Более редкие параметры для motion tuning, noise, spawn rules и логики конкретного профиля.",
                ["main.pluginDiagnostics"] = "Диагностика плагина",
                ["main.diag.status"] = "Статус",
                ["main.diag.assembly"] = "Сборка",
                ["main.diag.assemblyPath"] = "Путь к сборке",
                ["main.diag.entryType"] = "Entry type",
                ["main.diag.loadedAt"] = "Загружено",
                ["main.diag.lastError"] = "Последняя ошибка",
                ["main.diag.warning"] = "Предупреждение",
                ["main.diag.reload"] = "Перезагрузить",
                ["main.diag.revealFiles"] = "Показать файлы",
                ["main.diag.useSafeProfile"] = "Безопасный профиль",
                ["main.diag.status.loaded"] = "Загружено",
                ["main.diag.status.idle"] = "Ожидание",
                ["main.diag.status.error"] = "Ошибка",
                ["main.diag.status.broken"] = "Повреждено",
                ["main.diag.bool.yes"] = "да",
                ["main.diag.bool.no"] = "нет",
                ["main.diag.context"] = "Снимок курсора: {0} | Backdrop sample: {1} | Курсор видим: {2}",
                ["main.diag.warning.assemblyMissing"] = "DLL плагина отсутствует в ожидаемом каталоге. Повторно импортируйте или замените пакет плагина.",
                ["main.diag.warning.configIssue"] = "Импортированный профиль плагина не содержит обязательных runtime-метаданных. Повторно импортируйте плагин или замените его более новой сборкой.",
                ["main.diag.warning.runtimeError"] = "Runtime плагина завершился с ошибкой при загрузке или рендере. Сначала попробуйте перезагрузку, затем замену плагина, если ошибка сохраняется.",
                ["main.diag.warning.hiddenCursor"] = "Курсор сейчас скрыт. Плагины, привязанные к курсору, могут не рендериться, пока курсор снова не станет видимым.",
                ["main.diag.warning.noBackdrop"] = "Backdrop sampling сейчас недоступен. Плагины, которые искажают видимое изображение, могут выглядеть неполно.",
                ["main.diag.warning.noSnapshot"] = "Снимок курсора сейчас недоступен. Контурные плагины по форме курсора могут работать некорректно.",
                ["main.diag.warning.none"] = "Runtime-контекст выглядит корректно.",
                ["main.profiles"] = "Профили",
                ["main.profilesHint"] = "Встроенные стили отделены от импортированных DLL-плагинов, чтобы библиотеку было легче просматривать.",
                ["main.builtInProfiles"] = "Встроенные профили",
                ["main.importedPlugins"] = "Импортированные плагины",
                ["main.importShort"] = "Импорт",
                ["main.iconPlaceholder"] = "Иконка",
                ["main.autosaveReady"] = "Параметры синхронизируются автоматически.",
                ["main.noImportedPlugins"] = "Импортированных плагинов пока нет.",
                ["main.importedPluginsSummary"] = "Импортированные плагины отсортированы от самых новых ({0}).",
                ["main.builtInProfilesSummary"] = "Встроенных профилей: {0}."
            }
        };

    public IReadOnlyList<LocalizationOption> AvailableLanguages => SupportedLanguages;

    public string CurrentLanguageCode { get; private set; } = "en";

    public void Apply(LocalizationSettings settings)
    {
        CurrentLanguageCode = ResolveLanguageCode(settings);
        var culture = new CultureInfo(CurrentLanguageCode);
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        Thread.CurrentThread.CurrentCulture = culture;
        Thread.CurrentThread.CurrentUICulture = culture;
    }

    public string ResolveLanguageCode(LocalizationSettings settings)
    {
        if (settings.UseSystemLanguage)
        {
            return ResolveSystemLanguageCode();
        }

        return NormalizeLanguageCode(settings.LanguageCode);
    }

    public string ResolveSystemLanguageCode()
    {
        return NormalizeLanguageCode(CultureInfo.InstalledUICulture.TwoLetterISOLanguageName);
    }

    public string NormalizeLanguageCode(string? languageCode)
    {
        var normalized = string.IsNullOrWhiteSpace(languageCode) ? "en" : languageCode.Trim().ToLowerInvariant();
        return SupportedLanguages.Any(option => string.Equals(option.Code, normalized, StringComparison.OrdinalIgnoreCase))
            ? normalized
            : "en";
    }

    public string Get(string key)
    {
        if (Strings.TryGetValue(CurrentLanguageCode, out var languageStrings) &&
            languageStrings.TryGetValue(key, out var localized))
        {
            return localized;
        }

        return Strings["en"].TryGetValue(key, out var fallback) ? fallback : key;
    }
}

public sealed record LocalizationOption(string Code, string DisplayName)
{
    public override string ToString() => DisplayName;
}
